server:
  port: ${PORT:8082}

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service-admin
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - StripPrefix=3
        - id: user-service-classroom
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/classroom/**
          filters:
            - StripPrefix=3
        - id: user-service-group
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/group/**
          filters:
            - StripPrefix=3
        - id: user-service-organization
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/organization/**
          filters:
            - StripPrefix=3
        - id: user-service-users
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=3

        - id: web-api-rapport
          uri: http://localhost:8888
          predicates:
            - Path=/api/v1/rapport/**
          filters:
            - StripPrefix=3
        - id: web-api-github
          uri: http://localhost:8888
          predicates:
            - Path=/api/v1/github/**
          filters:
            - StripPrefix=3
        - id: web-api-chatbot
          uri: http://localhost:8888
          predicates:
            - Path=/api/v1/chatbot/**
          filters:
            - StripPrefix=3
        - id: web-api-reporting
          uri: http://localhost:8888
          predicates:
            - Path=/api/v1/reporting/**
          filters:
            - StripPrefix=3
        - id: web-api-pulls
          uri: http://localhost:8888
          predicates:
            - Path=/api/v1/pulls/**
          filters:
            - StripPrefix=3
        - id: web-api-organization
          uri: http://localhost:8888
          predicates:
            - Path=/api/v1/organization/**
          filters:
            - StripPrefix=3
        - id: web-api-events
          uri: http://localhost:8888
          predicates:
            - Path=/api/v1/events/**
          filters:
            - StripPrefix=3
        - id: web-api-commit
          uri: http://localhost:8888
          predicates:
            - Path=/api/v1/commit/**
          filters:
            - StripPrefix=3
        - id: web-api-branches
          uri: http://localhost:8888
          predicates:
            - Path=/api/v1/branches/**
          filters:
            - StripPrefix=3
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    com.example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://keycloak-auth:8080/realms/codesync-auth
#          jwk-set-uri: http://keycloak-auth:8080/realms/codesync-auth/protocol/openid-connect/certs
