spring.application.name=walid_bechri_rapport
server.port=8086
# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
openrouter.api.key=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
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions