spring.application.name=web-api


server.port=8888

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.profiles.active=dev


github.token=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