# Spring Boot Configuration
spring.application.name=web-api
server.port=8888


spring.datasource.url=jdbc:postgresql://localhost:5432/mission-entreprise
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true  # Pretty print SQL

github.api.events.url=https://api.github.com/events
logging.level.root=INFO
logging.level.com.example.githubevents=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

spring.profiles.active=dev

github.token=---
base_url=https://api.github.com
