eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}

server:
  port: 8761

spring:
  application:
    name: discovery-server