spring.application.name=backend
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/jira
spring.datasource.username=postgres
spring.datasource.password=boucha3ai
# Hibernate

spring.jpa.hibernate.ddl-auto=update
